
version = 2

# For containerd 1.7.28
[plugins."io.containerd.grpc.v1.cri".cni]
  bin_dir = "/var/lib/rancher/k3s/data/cni"

# For containerd 2.2
[plugins.'io.containerd.cri.v1.runtime'.cni]
  bin_dirs = [ "/var/lib/rancher/k3s/data/cni" ]

